// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/files/ActivityMsg.proto

package com.sy599.game.msg.serverPacket;

public final class ActivityMsg {
  private ActivityMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ActivityConfigInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活动ID
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活动ID
     * </pre>
     */
    int getId();

    // required string wanfas = 2;
    /**
     * <code>required string wanfas = 2;</code>
     *
     * <pre>
     * 支持的玩法ID -1表示所有玩家
     * </pre>
     */
    boolean hasWanfas();
    /**
     * <code>required string wanfas = 2;</code>
     *
     * <pre>
     * 支持的玩法ID -1表示所有玩家
     * </pre>
     */
    String getWanfas();
    /**
     * <code>required string wanfas = 2;</code>
     *
     * <pre>
     * 支持的玩法ID -1表示所有玩家
     * </pre>
     */
    com.google.protobuf.ByteString
        getWanfasBytes();

    // required int32 type = 3;
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     * 活动类型 0永久活动 1时限活动
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     * 活动类型 0永久活动 1时限活动
     * </pre>
     */
    int getType();

    // required string activityName = 4;
    /**
     * <code>required string activityName = 4;</code>
     *
     * <pre>
     * 活动名称
     * </pre>
     */
    boolean hasActivityName();
    /**
     * <code>required string activityName = 4;</code>
     *
     * <pre>
     * 活动名称
     * </pre>
     */
    String getActivityName();
    /**
     * <code>required string activityName = 4;</code>
     *
     * <pre>
     * 活动名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getActivityNameBytes();

    // required string startTime = 5;
    /**
     * <code>required string startTime = 5;</code>
     *
     * <pre>
     * 活动开始时间
     * </pre>
     */
    boolean hasStartTime();
    /**
     * <code>required string startTime = 5;</code>
     *
     * <pre>
     * 活动开始时间
     * </pre>
     */
    String getStartTime();
    /**
     * <code>required string startTime = 5;</code>
     *
     * <pre>
     * 活动开始时间
     * </pre>
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    // required string endTime = 6;
    /**
     * <code>required string endTime = 6;</code>
     *
     * <pre>
     * 活动结束时间
     * </pre>
     */
    boolean hasEndTime();
    /**
     * <code>required string endTime = 6;</code>
     *
     * <pre>
     * 活动结束时间
     * </pre>
     */
    String getEndTime();
    /**
     * <code>required string endTime = 6;</code>
     *
     * <pre>
     * 活动结束时间
     * </pre>
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();

    // required string params = 7;
    /**
     * <code>required string params = 7;</code>
     *
     * <pre>
     * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
     * </pre>
     */
    boolean hasParams();
    /**
     * <code>required string params = 7;</code>
     *
     * <pre>
     * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
     * </pre>
     */
    String getParams();
    /**
     * <code>required string params = 7;</code>
     *
     * <pre>
     * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
     * </pre>
     */
    com.google.protobuf.ByteString
        getParamsBytes();

    // required string desc = 8;
    /**
     * <code>required string desc = 8;</code>
     *
     * <pre>
     * 活动描叙
     * </pre>
     */
    boolean hasDesc();
    /**
     * <code>required string desc = 8;</code>
     *
     * <pre>
     * 活动描叙
     * </pre>
     */
    String getDesc();
    /**
     * <code>required string desc = 8;</code>
     *
     * <pre>
     * 活动描叙
     * </pre>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    // optional int32 singleEnter = 9;
    /**
     * <code>optional int32 singleEnter = 9;</code>
     *
     * <pre>
     * 是否单独入口活动 1单独入口活动 0活动专区活动
     * </pre>
     */
    boolean hasSingleEnter();
    /**
     * <code>optional int32 singleEnter = 9;</code>
     *
     * <pre>
     * 是否单独入口活动 1单独入口活动 0活动专区活动
     * </pre>
     */
    int getSingleEnter();
  }
  /**
   * Protobuf type {@code com.sy599.game.msg.serverPacket.ActivityConfigInfo}
   *
   * <pre>
   *活动配置信息
   * </pre>
   */
  public static final class ActivityConfigInfo extends
      com.google.protobuf.GeneratedMessage
      implements ActivityConfigInfoOrBuilder {
    // Use ActivityConfigInfo.newBuilder() to construct.
    private ActivityConfigInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ActivityConfigInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ActivityConfigInfo defaultInstance;
    public static ActivityConfigInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ActivityConfigInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ActivityConfigInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              wanfas_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              activityName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              startTime_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              endTime_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              params_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              desc_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              singleEnter_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ActivityMsg.internal_static_com_sy599_game_msg_serverPacket_ActivityConfigInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ActivityMsg.internal_static_com_sy599_game_msg_serverPacket_ActivityConfigInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ActivityConfigInfo.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ActivityConfigInfo> PARSER =
        new com.google.protobuf.AbstractParser<ActivityConfigInfo>() {
      public ActivityConfigInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActivityConfigInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ActivityConfigInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活动ID
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活动ID
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // required string wanfas = 2;
    public static final int WANFAS_FIELD_NUMBER = 2;
    private Object wanfas_;
    /**
     * <code>required string wanfas = 2;</code>
     *
     * <pre>
     * 支持的玩法ID -1表示所有玩家
     * </pre>
     */
    public boolean hasWanfas() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string wanfas = 2;</code>
     *
     * <pre>
     * 支持的玩法ID -1表示所有玩家
     * </pre>
     */
    public String getWanfas() {
      Object ref = wanfas_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          wanfas_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string wanfas = 2;</code>
     *
     * <pre>
     * 支持的玩法ID -1表示所有玩家
     * </pre>
     */
    public com.google.protobuf.ByteString
        getWanfasBytes() {
      Object ref = wanfas_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        wanfas_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     * 活动类型 0永久活动 1时限活动
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     * 活动类型 0永久活动 1时限活动
     * </pre>
     */
    public int getType() {
      return type_;
    }

    // required string activityName = 4;
    public static final int ACTIVITYNAME_FIELD_NUMBER = 4;
    private Object activityName_;
    /**
     * <code>required string activityName = 4;</code>
     *
     * <pre>
     * 活动名称
     * </pre>
     */
    public boolean hasActivityName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string activityName = 4;</code>
     *
     * <pre>
     * 活动名称
     * </pre>
     */
    public String getActivityName() {
      Object ref = activityName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          activityName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string activityName = 4;</code>
     *
     * <pre>
     * 活动名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getActivityNameBytes() {
      Object ref = activityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        activityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string startTime = 5;
    public static final int STARTTIME_FIELD_NUMBER = 5;
    private Object startTime_;
    /**
     * <code>required string startTime = 5;</code>
     *
     * <pre>
     * 活动开始时间
     * </pre>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string startTime = 5;</code>
     *
     * <pre>
     * 活动开始时间
     * </pre>
     */
    public String getStartTime() {
      Object ref = startTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string startTime = 5;</code>
     *
     * <pre>
     * 活动开始时间
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      Object ref = startTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string endTime = 6;
    public static final int ENDTIME_FIELD_NUMBER = 6;
    private Object endTime_;
    /**
     * <code>required string endTime = 6;</code>
     *
     * <pre>
     * 活动结束时间
     * </pre>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string endTime = 6;</code>
     *
     * <pre>
     * 活动结束时间
     * </pre>
     */
    public String getEndTime() {
      Object ref = endTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string endTime = 6;</code>
     *
     * <pre>
     * 活动结束时间
     * </pre>
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string params = 7;
    public static final int PARAMS_FIELD_NUMBER = 7;
    private Object params_;
    /**
     * <code>required string params = 7;</code>
     *
     * <pre>
     * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
     * </pre>
     */
    public boolean hasParams() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string params = 7;</code>
     *
     * <pre>
     * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
     * </pre>
     */
    public String getParams() {
      Object ref = params_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          params_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string params = 7;</code>
     *
     * <pre>
     * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getParamsBytes() {
      Object ref = params_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        params_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string desc = 8;
    public static final int DESC_FIELD_NUMBER = 8;
    private Object desc_;
    /**
     * <code>required string desc = 8;</code>
     *
     * <pre>
     * 活动描叙
     * </pre>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string desc = 8;</code>
     *
     * <pre>
     * 活动描叙
     * </pre>
     */
    public String getDesc() {
      Object ref = desc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string desc = 8;</code>
     *
     * <pre>
     * 活动描叙
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 singleEnter = 9;
    public static final int SINGLEENTER_FIELD_NUMBER = 9;
    private int singleEnter_;
    /**
     * <code>optional int32 singleEnter = 9;</code>
     *
     * <pre>
     * 是否单独入口活动 1单独入口活动 0活动专区活动
     * </pre>
     */
    public boolean hasSingleEnter() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 singleEnter = 9;</code>
     *
     * <pre>
     * 是否单独入口活动 1单独入口活动 0活动专区活动
     * </pre>
     */
    public int getSingleEnter() {
      return singleEnter_;
    }

    private void initFields() {
      id_ = 0;
      wanfas_ = "";
      type_ = 0;
      activityName_ = "";
      startTime_ = "";
      endTime_ = "";
      params_ = "";
      desc_ = "";
      singleEnter_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWanfas()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActivityName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParams()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDesc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getWanfasBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getActivityNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getEndTimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getParamsBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getDescBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, singleEnter_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getWanfasBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getActivityNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getEndTimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getParamsBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getDescBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, singleEnter_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ActivityConfigInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ActivityConfigInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ActivityConfigInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ActivityConfigInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ActivityConfigInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ActivityConfigInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ActivityConfigInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ActivityConfigInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ActivityConfigInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ActivityConfigInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ActivityConfigInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sy599.game.msg.serverPacket.ActivityConfigInfo}
     *
     * <pre>
     *活动配置信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ActivityConfigInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ActivityMsg.internal_static_com_sy599_game_msg_serverPacket_ActivityConfigInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ActivityMsg.internal_static_com_sy599_game_msg_serverPacket_ActivityConfigInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ActivityConfigInfo.class, Builder.class);
      }

      // Construct using com.sy599.game.msg.serverPacket.ActivityMsg.ActivityConfigInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        wanfas_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        activityName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        startTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        endTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        params_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        singleEnter_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ActivityMsg.internal_static_com_sy599_game_msg_serverPacket_ActivityConfigInfo_descriptor;
      }

      public ActivityConfigInfo getDefaultInstanceForType() {
        return ActivityConfigInfo.getDefaultInstance();
      }

      public ActivityConfigInfo build() {
        ActivityConfigInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ActivityConfigInfo buildPartial() {
        ActivityConfigInfo result = new ActivityConfigInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.wanfas_ = wanfas_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.activityName_ = activityName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.params_ = params_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.singleEnter_ = singleEnter_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ActivityConfigInfo) {
          return mergeFrom((ActivityConfigInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ActivityConfigInfo other) {
        if (other == ActivityConfigInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasWanfas()) {
          bitField0_ |= 0x00000002;
          wanfas_ = other.wanfas_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasActivityName()) {
          bitField0_ |= 0x00000008;
          activityName_ = other.activityName_;
          onChanged();
        }
        if (other.hasStartTime()) {
          bitField0_ |= 0x00000010;
          startTime_ = other.startTime_;
          onChanged();
        }
        if (other.hasEndTime()) {
          bitField0_ |= 0x00000020;
          endTime_ = other.endTime_;
          onChanged();
        }
        if (other.hasParams()) {
          bitField0_ |= 0x00000040;
          params_ = other.params_;
          onChanged();
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000080;
          desc_ = other.desc_;
          onChanged();
        }
        if (other.hasSingleEnter()) {
          setSingleEnter(other.getSingleEnter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasWanfas()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasActivityName()) {
          
          return false;
        }
        if (!hasStartTime()) {
          
          return false;
        }
        if (!hasEndTime()) {
          
          return false;
        }
        if (!hasParams()) {
          
          return false;
        }
        if (!hasDesc()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ActivityConfigInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ActivityConfigInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活动ID
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活动ID
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活动ID
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活动ID
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string wanfas = 2;
      private Object wanfas_ = "";
      /**
       * <code>required string wanfas = 2;</code>
       *
       * <pre>
       * 支持的玩法ID -1表示所有玩家
       * </pre>
       */
      public boolean hasWanfas() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string wanfas = 2;</code>
       *
       * <pre>
       * 支持的玩法ID -1表示所有玩家
       * </pre>
       */
      public String getWanfas() {
        Object ref = wanfas_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          wanfas_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string wanfas = 2;</code>
       *
       * <pre>
       * 支持的玩法ID -1表示所有玩家
       * </pre>
       */
      public com.google.protobuf.ByteString
          getWanfasBytes() {
        Object ref = wanfas_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          wanfas_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string wanfas = 2;</code>
       *
       * <pre>
       * 支持的玩法ID -1表示所有玩家
       * </pre>
       */
      public Builder setWanfas(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        wanfas_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string wanfas = 2;</code>
       *
       * <pre>
       * 支持的玩法ID -1表示所有玩家
       * </pre>
       */
      public Builder clearWanfas() {
        bitField0_ = (bitField0_ & ~0x00000002);
        wanfas_ = getDefaultInstance().getWanfas();
        onChanged();
        return this;
      }
      /**
       * <code>required string wanfas = 2;</code>
       *
       * <pre>
       * 支持的玩法ID -1表示所有玩家
       * </pre>
       */
      public Builder setWanfasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        wanfas_ = value;
        onChanged();
        return this;
      }

      // required int32 type = 3;
      private int type_ ;
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       * 活动类型 0永久活动 1时限活动
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       * 活动类型 0永久活动 1时限活动
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       * 活动类型 0永久活动 1时限活动
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       * 活动类型 0永久活动 1时限活动
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      // required string activityName = 4;
      private Object activityName_ = "";
      /**
       * <code>required string activityName = 4;</code>
       *
       * <pre>
       * 活动名称
       * </pre>
       */
      public boolean hasActivityName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string activityName = 4;</code>
       *
       * <pre>
       * 活动名称
       * </pre>
       */
      public String getActivityName() {
        Object ref = activityName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          activityName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string activityName = 4;</code>
       *
       * <pre>
       * 活动名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getActivityNameBytes() {
        Object ref = activityName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          activityName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string activityName = 4;</code>
       *
       * <pre>
       * 活动名称
       * </pre>
       */
      public Builder setActivityName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        activityName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string activityName = 4;</code>
       *
       * <pre>
       * 活动名称
       * </pre>
       */
      public Builder clearActivityName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        activityName_ = getDefaultInstance().getActivityName();
        onChanged();
        return this;
      }
      /**
       * <code>required string activityName = 4;</code>
       *
       * <pre>
       * 活动名称
       * </pre>
       */
      public Builder setActivityNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        activityName_ = value;
        onChanged();
        return this;
      }

      // required string startTime = 5;
      private Object startTime_ = "";
      /**
       * <code>required string startTime = 5;</code>
       *
       * <pre>
       * 活动开始时间
       * </pre>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string startTime = 5;</code>
       *
       * <pre>
       * 活动开始时间
       * </pre>
       */
      public String getStartTime() {
        Object ref = startTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string startTime = 5;</code>
       *
       * <pre>
       * 活动开始时间
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string startTime = 5;</code>
       *
       * <pre>
       * 活动开始时间
       * </pre>
       */
      public Builder setStartTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string startTime = 5;</code>
       *
       * <pre>
       * 活动开始时间
       * </pre>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string startTime = 5;</code>
       *
       * <pre>
       * 活动开始时间
       * </pre>
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        startTime_ = value;
        onChanged();
        return this;
      }

      // required string endTime = 6;
      private Object endTime_ = "";
      /**
       * <code>required string endTime = 6;</code>
       *
       * <pre>
       * 活动结束时间
       * </pre>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string endTime = 6;</code>
       *
       * <pre>
       * 活动结束时间
       * </pre>
       */
      public String getEndTime() {
        Object ref = endTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string endTime = 6;</code>
       *
       * <pre>
       * 活动结束时间
       * </pre>
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string endTime = 6;</code>
       *
       * <pre>
       * 活动结束时间
       * </pre>
       */
      public Builder setEndTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string endTime = 6;</code>
       *
       * <pre>
       * 活动结束时间
       * </pre>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string endTime = 6;</code>
       *
       * <pre>
       * 活动结束时间
       * </pre>
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        endTime_ = value;
        onChanged();
        return this;
      }

      // required string params = 7;
      private Object params_ = "";
      /**
       * <code>required string params = 7;</code>
       *
       * <pre>
       * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
       * </pre>
       */
      public boolean hasParams() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string params = 7;</code>
       *
       * <pre>
       * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
       * </pre>
       */
      public String getParams() {
        Object ref = params_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          params_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string params = 7;</code>
       *
       * <pre>
       * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getParamsBytes() {
        Object ref = params_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          params_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string params = 7;</code>
       *
       * <pre>
       * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
       * </pre>
       */
      public Builder setParams(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        params_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string params = 7;</code>
       *
       * <pre>
       * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
       * </pre>
       */
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000040);
        params_ = getDefaultInstance().getParams();
        onChanged();
        return this;
      }
      /**
       * <code>required string params = 7;</code>
       *
       * <pre>
       * 活动相关参数  包括活动达成相关参数comParams 活动奖励配置参数rewardParams  玩家个人活动相关参数 
       * </pre>
       */
      public Builder setParamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        params_ = value;
        onChanged();
        return this;
      }

      // required string desc = 8;
      private Object desc_ = "";
      /**
       * <code>required string desc = 8;</code>
       *
       * <pre>
       * 活动描叙
       * </pre>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string desc = 8;</code>
       *
       * <pre>
       * 活动描叙
       * </pre>
       */
      public String getDesc() {
        Object ref = desc_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string desc = 8;</code>
       *
       * <pre>
       * 活动描叙
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string desc = 8;</code>
       *
       * <pre>
       * 活动描叙
       * </pre>
       */
      public Builder setDesc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 8;</code>
       *
       * <pre>
       * 活动描叙
       * </pre>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000080);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 8;</code>
       *
       * <pre>
       * 活动描叙
       * </pre>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        desc_ = value;
        onChanged();
        return this;
      }

      // optional int32 singleEnter = 9;
      private int singleEnter_ ;
      /**
       * <code>optional int32 singleEnter = 9;</code>
       *
       * <pre>
       * 是否单独入口活动 1单独入口活动 0活动专区活动
       * </pre>
       */
      public boolean hasSingleEnter() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 singleEnter = 9;</code>
       *
       * <pre>
       * 是否单独入口活动 1单独入口活动 0活动专区活动
       * </pre>
       */
      public int getSingleEnter() {
        return singleEnter_;
      }
      /**
       * <code>optional int32 singleEnter = 9;</code>
       *
       * <pre>
       * 是否单独入口活动 1单独入口活动 0活动专区活动
       * </pre>
       */
      public Builder setSingleEnter(int value) {
        bitField0_ |= 0x00000100;
        singleEnter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 singleEnter = 9;</code>
       *
       * <pre>
       * 是否单独入口活动 1单独入口活动 0活动专区活动
       * </pre>
       */
      public Builder clearSingleEnter() {
        bitField0_ = (bitField0_ & ~0x00000100);
        singleEnter_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sy599.game.msg.serverPacket.ActivityConfigInfo)
    }

    static {
      defaultInstance = new ActivityConfigInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sy599.game.msg.serverPacket.ActivityConfigInfo)
  }

  public interface ActivityListsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
     *
     * <pre>
     * 开启的活动信息列表
     * </pre>
     */
    java.util.List<ActivityConfigInfo>
        getConfigInfosList();
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
     *
     * <pre>
     * 开启的活动信息列表
     * </pre>
     */
    ActivityConfigInfo getConfigInfos(int index);
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
     *
     * <pre>
     * 开启的活动信息列表
     * </pre>
     */
    int getConfigInfosCount();
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
     *
     * <pre>
     * 开启的活动信息列表
     * </pre>
     */
    java.util.List<? extends ActivityConfigInfoOrBuilder>
        getConfigInfosOrBuilderList();
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
     *
     * <pre>
     * 开启的活动信息列表
     * </pre>
     */
    ActivityConfigInfoOrBuilder getConfigInfosOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code com.sy599.game.msg.serverPacket.ActivityLists}
   *
   * <pre>
   *精彩活动面板信息
   * </pre>
   */
  public static final class ActivityLists extends
      com.google.protobuf.GeneratedMessage
      implements ActivityListsOrBuilder {
    // Use ActivityLists.newBuilder() to construct.
    private ActivityLists(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ActivityLists(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ActivityLists defaultInstance;
    public static ActivityLists getDefaultInstance() {
      return defaultInstance;
    }

    public ActivityLists getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ActivityLists(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                configInfos_ = new java.util.ArrayList<ActivityConfigInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              configInfos_.add(input.readMessage(ActivityConfigInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          configInfos_ = java.util.Collections.unmodifiableList(configInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ActivityMsg.internal_static_com_sy599_game_msg_serverPacket_ActivityLists_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ActivityMsg.internal_static_com_sy599_game_msg_serverPacket_ActivityLists_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ActivityLists.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ActivityLists> PARSER =
        new com.google.protobuf.AbstractParser<ActivityLists>() {
      public ActivityLists parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActivityLists(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ActivityLists> getParserForType() {
      return PARSER;
    }

    // repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;
    public static final int CONFIGINFOS_FIELD_NUMBER = 1;
    private java.util.List<ActivityConfigInfo> configInfos_;
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
     *
     * <pre>
     * 开启的活动信息列表
     * </pre>
     */
    public java.util.List<ActivityConfigInfo> getConfigInfosList() {
      return configInfos_;
    }
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
     *
     * <pre>
     * 开启的活动信息列表
     * </pre>
     */
    public java.util.List<? extends ActivityConfigInfoOrBuilder>
        getConfigInfosOrBuilderList() {
      return configInfos_;
    }
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
     *
     * <pre>
     * 开启的活动信息列表
     * </pre>
     */
    public int getConfigInfosCount() {
      return configInfos_.size();
    }
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
     *
     * <pre>
     * 开启的活动信息列表
     * </pre>
     */
    public ActivityConfigInfo getConfigInfos(int index) {
      return configInfos_.get(index);
    }
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
     *
     * <pre>
     * 开启的活动信息列表
     * </pre>
     */
    public ActivityConfigInfoOrBuilder getConfigInfosOrBuilder(
        int index) {
      return configInfos_.get(index);
    }

    private void initFields() {
      configInfos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getConfigInfosCount(); i++) {
        if (!getConfigInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < configInfos_.size(); i++) {
        output.writeMessage(1, configInfos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < configInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, configInfos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ActivityLists parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ActivityLists parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ActivityLists parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ActivityLists parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ActivityLists parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ActivityLists parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ActivityLists parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ActivityLists parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ActivityLists parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ActivityLists parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ActivityLists prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sy599.game.msg.serverPacket.ActivityLists}
     *
     * <pre>
     *精彩活动面板信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ActivityListsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ActivityMsg.internal_static_com_sy599_game_msg_serverPacket_ActivityLists_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ActivityMsg.internal_static_com_sy599_game_msg_serverPacket_ActivityLists_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ActivityLists.class, Builder.class);
      }

      // Construct using com.sy599.game.msg.serverPacket.ActivityMsg.ActivityLists.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getConfigInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (configInfosBuilder_ == null) {
          configInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          configInfosBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ActivityMsg.internal_static_com_sy599_game_msg_serverPacket_ActivityLists_descriptor;
      }

      public ActivityLists getDefaultInstanceForType() {
        return ActivityLists.getDefaultInstance();
      }

      public ActivityLists build() {
        ActivityLists result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ActivityLists buildPartial() {
        ActivityLists result = new ActivityLists(this);
        int from_bitField0_ = bitField0_;
        if (configInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            configInfos_ = java.util.Collections.unmodifiableList(configInfos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.configInfos_ = configInfos_;
        } else {
          result.configInfos_ = configInfosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ActivityLists) {
          return mergeFrom((ActivityLists)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ActivityLists other) {
        if (other == ActivityLists.getDefaultInstance()) return this;
        if (configInfosBuilder_ == null) {
          if (!other.configInfos_.isEmpty()) {
            if (configInfos_.isEmpty()) {
              configInfos_ = other.configInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureConfigInfosIsMutable();
              configInfos_.addAll(other.configInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.configInfos_.isEmpty()) {
            if (configInfosBuilder_.isEmpty()) {
              configInfosBuilder_.dispose();
              configInfosBuilder_ = null;
              configInfos_ = other.configInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              configInfosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getConfigInfosFieldBuilder() : null;
            } else {
              configInfosBuilder_.addAllMessages(other.configInfos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getConfigInfosCount(); i++) {
          if (!getConfigInfos(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ActivityLists parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ActivityLists) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;
      private java.util.List<ActivityConfigInfo> configInfos_ =
        java.util.Collections.emptyList();
      private void ensureConfigInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          configInfos_ = new java.util.ArrayList<ActivityConfigInfo>(configInfos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ActivityConfigInfo, ActivityConfigInfo.Builder, ActivityConfigInfoOrBuilder> configInfosBuilder_;

      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public java.util.List<ActivityConfigInfo> getConfigInfosList() {
        if (configInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(configInfos_);
        } else {
          return configInfosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public int getConfigInfosCount() {
        if (configInfosBuilder_ == null) {
          return configInfos_.size();
        } else {
          return configInfosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public ActivityConfigInfo getConfigInfos(int index) {
        if (configInfosBuilder_ == null) {
          return configInfos_.get(index);
        } else {
          return configInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public Builder setConfigInfos(
          int index, ActivityConfigInfo value) {
        if (configInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigInfosIsMutable();
          configInfos_.set(index, value);
          onChanged();
        } else {
          configInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public Builder setConfigInfos(
          int index, ActivityConfigInfo.Builder builderForValue) {
        if (configInfosBuilder_ == null) {
          ensureConfigInfosIsMutable();
          configInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          configInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public Builder addConfigInfos(ActivityConfigInfo value) {
        if (configInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigInfosIsMutable();
          configInfos_.add(value);
          onChanged();
        } else {
          configInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public Builder addConfigInfos(
          int index, ActivityConfigInfo value) {
        if (configInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigInfosIsMutable();
          configInfos_.add(index, value);
          onChanged();
        } else {
          configInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public Builder addConfigInfos(
          ActivityConfigInfo.Builder builderForValue) {
        if (configInfosBuilder_ == null) {
          ensureConfigInfosIsMutable();
          configInfos_.add(builderForValue.build());
          onChanged();
        } else {
          configInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public Builder addConfigInfos(
          int index, ActivityConfigInfo.Builder builderForValue) {
        if (configInfosBuilder_ == null) {
          ensureConfigInfosIsMutable();
          configInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          configInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public Builder addAllConfigInfos(
          Iterable<? extends ActivityConfigInfo> values) {
        if (configInfosBuilder_ == null) {
          ensureConfigInfosIsMutable();
          super.addAll(values, configInfos_);
          onChanged();
        } else {
          configInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public Builder clearConfigInfos() {
        if (configInfosBuilder_ == null) {
          configInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          configInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public Builder removeConfigInfos(int index) {
        if (configInfosBuilder_ == null) {
          ensureConfigInfosIsMutable();
          configInfos_.remove(index);
          onChanged();
        } else {
          configInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public ActivityConfigInfo.Builder getConfigInfosBuilder(
          int index) {
        return getConfigInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public ActivityConfigInfoOrBuilder getConfigInfosOrBuilder(
          int index) {
        if (configInfosBuilder_ == null) {
          return configInfos_.get(index);  } else {
          return configInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public java.util.List<? extends ActivityConfigInfoOrBuilder>
           getConfigInfosOrBuilderList() {
        if (configInfosBuilder_ != null) {
          return configInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(configInfos_);
        }
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public ActivityConfigInfo.Builder addConfigInfosBuilder() {
        return getConfigInfosFieldBuilder().addBuilder(
            ActivityConfigInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public ActivityConfigInfo.Builder addConfigInfosBuilder(
          int index) {
        return getConfigInfosFieldBuilder().addBuilder(
            index, ActivityConfigInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.ActivityConfigInfo configInfos = 1;</code>
       *
       * <pre>
       * 开启的活动信息列表
       * </pre>
       */
      public java.util.List<ActivityConfigInfo.Builder>
           getConfigInfosBuilderList() {
        return getConfigInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ActivityConfigInfo, ActivityConfigInfo.Builder, ActivityConfigInfoOrBuilder>
          getConfigInfosFieldBuilder() {
        if (configInfosBuilder_ == null) {
          configInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ActivityConfigInfo, ActivityConfigInfo.Builder, ActivityConfigInfoOrBuilder>(
                  configInfos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          configInfos_ = null;
        }
        return configInfosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.sy599.game.msg.serverPacket.ActivityLists)
    }

    static {
      defaultInstance = new ActivityLists(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sy599.game.msg.serverPacket.ActivityLists)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sy599_game_msg_serverPacket_ActivityConfigInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sy599_game_msg_serverPacket_ActivityConfigInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sy599_game_msg_serverPacket_ActivityLists_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sy599_game_msg_serverPacket_ActivityLists_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\035proto/files/ActivityMsg.proto\022\037com.sy5" +
      "99.game.msg.serverPacket\"\253\001\n\022ActivityCon" +
      "figInfo\022\n\n\002id\030\001 \002(\005\022\016\n\006wanfas\030\002 \002(\t\022\014\n\004t" +
      "ype\030\003 \002(\005\022\024\n\014activityName\030\004 \002(\t\022\021\n\tstart" +
      "Time\030\005 \002(\t\022\017\n\007endTime\030\006 \002(\t\022\016\n\006params\030\007 " +
      "\002(\t\022\014\n\004desc\030\010 \002(\t\022\023\n\013singleEnter\030\t \001(\005\"Y" +
      "\n\rActivityLists\022H\n\013configInfos\030\001 \003(\01323.c" +
      "om.sy599.game.msg.serverPacket.ActivityC" +
      "onfigInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_sy599_game_msg_serverPacket_ActivityConfigInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_sy599_game_msg_serverPacket_ActivityConfigInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sy599_game_msg_serverPacket_ActivityConfigInfo_descriptor,
              new String[] { "Id", "Wanfas", "Type", "ActivityName", "StartTime", "EndTime", "Params", "Desc", "SingleEnter", });
          internal_static_com_sy599_game_msg_serverPacket_ActivityLists_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_sy599_game_msg_serverPacket_ActivityLists_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sy599_game_msg_serverPacket_ActivityLists_descriptor,
              new String[] { "ConfigInfos", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
